apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helm-release

resources:
  - ../../base

secretGenerator:
  - name: pgp-keys
    files:
      - private.pgp=private.pgp

generatorOptions:
  disableNameSuffixHash: true
